// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Prom = require("bs-prom/src/Prom.bs.js");
var Server_Pg = require("./Server_Pg.bs.js");
var SqlBricksPostgres = require("sql-bricks-postgres");

function _connect(pool) {
  return pool.connect();
}

function perform(pool, bricks) {
  return Prom.map(Server_Pg.Pool[/* query */0](pool, bricks.toParams()), (function (a) {
                return a.rows;
              }));
}

function performRaw(pool, values, text) {
  var fragment = values !== undefined ? SqlBricksPostgres(text, values[1]) : SqlBricksPostgres(text);
  return Prom.map(Server_Pg.Pool[/* query */0](pool, {
                  text: fragment.str,
                  values: fragment.vals
                }), (function (a) {
                return a.rows;
              }));
}

var Bricks = 0;

exports.Bricks = Bricks;
exports._connect = _connect;
exports.perform = perform;
exports.performRaw = performRaw;
/* Server_Pg Not a pure module */
