// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Js_dict = require("bs-platform/lib/js/js_dict.js");
var Process = require("process");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function fromEnv(key, $$default) {
  var env = Process.env;
  var match = Js_dict.get(env, key);
  if (match !== undefined) {
    return match;
  } else {
    return $$default;
  }
}

var envName = fromEnv("NODE_ENV", "development");

var isProduction = envName === "production";

var isDev = envName === "dev" || envName === "development";

var logLevel = fromEnv("LOG_LEVEL", isProduction ? "info" : "silly");

var databaseUrl = fromEnv("DATABASE_URL", "postgres://postgres:password@localhost:5432/postgres");

var port = Caml_format.caml_int_of_string(fromEnv("PORT", "3000"));

exports.fromEnv = fromEnv;
exports.envName = envName;
exports.isProduction = isProduction;
exports.isDev = isDev;
exports.logLevel = logLevel;
exports.databaseUrl = databaseUrl;
exports.port = port;
/* envName Not a pure module */
