// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Express = require("bs-express/src/Express.js");
var MiddlewareAsCompleteJs = require("./middlewareAsComplete.js");

function queryJson(req) {
  return Express.$$Request[/* query */19](req);
}

function middlewareAsComplete(prim, prim$1, prim$2) {
  return MiddlewareAsCompleteJs(prim, prim$1, prim$2);
}

exports.queryJson = queryJson;
exports.middlewareAsComplete = middlewareAsComplete;
/* Express Not a pure module */
