// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var MiddlewareAsCompleteJs = require("./middlewareAsComplete.js");

function queryJson(req) {
  return req.query;
}

function middlewareAsComplete(prim, prim$1, prim$2) {
  return MiddlewareAsCompleteJs(prim, prim$1, prim$2);
}

exports.queryJson = queryJson;
exports.middlewareAsComplete = middlewareAsComplete;
/* ./middlewareAsComplete.js Not a pure module */
